### ISSUE TITLE
error handling

### ISSUE THREAD

**Issue by marcelo321** [s0md3v/uro#11]
So I added uro to my workflow and after a while I got this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/uro", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/uro/uro.py", line 139, in main
    if matches_patterns(path):
  File "/usr/local/lib/python3.8/dist-packages/uro/uro.py", line 107, in matches_patterns
    if re.search(pattern, path):
  File "/usr/lib/python3.8/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 836, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 369
```

It is happening to me with different inputs so seems to be something that happens often

**Comment by s0md3v** [comment]
This issue has been fixed already, reinstall uro.
