### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by marcelo321** [s0md3v/uro#23]
I have been encountering this issue:

```
  File "/usr/local/bin/uro", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/uro/uro.py", line 151, in main
    print(host + path + dict_to_params(param))
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/bin/uro", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/uro/uro.py", line 161, in main
    print(host + path)
BrokenPipeError: [Errno 32] Broken pipe
```

Any idea why would it be?

**Comment by s0md3v** [comment]
Apparently this isn't uro's fault, it happens when the program providing input via stdin/pipe exits abruptly or does something weird.
