### ISSUE TITLE
ValueError: Invalid IPv6 URL

### ISSUE THREAD

**Issue by JustReadingSome** [s0md3v/uro#31]
cat all_urls.txt | uro
-------------------------------
Traceback (most recent call last):
  File "/usr/local/bin/uro", line 11, in <module>
    load_entry_point('uro==0.0.4', 'console_scripts', 'uro')()
  File "/usr/local/lib/python3.10/dist-packages/uro-0.0.4-py3.10.egg/uro/uro.py", line 124, in main
  File "/usr/lib/python3.10/urllib/parse.py", line 392, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.10/urllib/parse.py", line 483, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL

**Comment by JustReadingSome** [comment]
Hello, I don't know why I get this error. I also tried to install uro with different version of python but that didn't work.

**Comment by JustReadingSome** [comment]
The problem was because of "\x1b[0m" characters at the end of URLs. So if anybody had this problem you can handle it with python and remove "\x1b[0m" from URLs.

**Comment by s0md3v** [comment]
This has nothing to do with uro, your input is malformed.
