### ISSUE TITLE
All of a sudden wont work 

### ISSUE THREAD

**Issue by a6thmfsin** [s0md3v/uro#36]
Traceback (most recent call last):
  File "/usr/bin/uro", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/greyhound/.local/lib/python3.11/site-packages/uro/uro.py", line 163, in main
    process_url(parsed_url)
  File "/home/greyhound/.local/lib/python3.11/site-packages/uro/uro.py", line 136, in process_url
    new_params = [param for param in params.keys() if param not in params_seen]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/greyhound/.local/lib/python3.11/site-packages/uro/uro.py", line 136, in <listcomp>
    new_params = [param for param in params.keys() if param not in params_seen]
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

Ive tried tried setting aliases, changing paths etc wont work..

**Comment by a6thmfsin** [comment]
Reinstalling, uninstalling both as pip, pip3, superuser idk what else i could do all of a sudden stopped working.

**Comment by a6thmfsin** [comment]
just running uro as alias or as uro i get this (without piping it) [ERROR] No input file or stdin. So seems it should work.
